import './globals.css'
import { Kumbh_Sans } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const kumbh = Kumbh_Sans({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={kumbh.className || 'font-sans'} lang="en">
      <body>{children}</body>
    </html>
  )
}
